import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import BoggleGameBoard from '../components/BoggleGameBoard'
import Solutions from '../components/Solutions';
import checkForSolution from '../scrpts/BoggleUtils'
import { useState } from 'react'
export default function Home() {
  const [solutionsToRender, setSolutionsToRender] = useState([]);
  const [gameBoard, setGameBoard] = useState([]);

  const handleClick = () => {
    const solutionStrToTest = document.getElementById('dictionaryInput').value;
    if(solutionStrToTest.length > 0){
      const currSolutions = checkForSolution(gameBoard,solutionStrToTest.split(',').map(words => words.toUpperCase()));
      setSolutionsToRender(currSolutions)
    }

  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.gameContainer}>
        <div>
          <h1>Boggle Board 4 x 4</h1>
        </div>
        <div>
          <Solutions solutions={solutionsToRender}/>
        </div>
        <div>
          <BoggleGameBoard setGameBoard={setGameBoard} />
        </div>
        <div> 
          <div className={styles.playerInput}>
            <h2>Please make a list of words</h2>
            <i>List possible matches by comma seperated list i.e. one,two,three,....</i>
            <textarea  rows ='6' id='dictionaryInput'></textarea>
            <button onClick={handleClick} >Check Answers</button>
          </div>
        </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
/**
 *  if(solutions.length === 0){
      document.getElementById('solutionItem').innerHTML = `<div><h3>No solutions Found</h3<div>`
  }else {
      document.getElementById('solutionItem').innerHTML = `<div><h3>Solutions found : ${solutions.length}</h3><p>Items in dictionary: ${solutions.join().replaceAll(',',', ')}</p><div>`
  }b
 */